"""The cohort kit: the skill, its references, the schedule generator, the alert script.

Two kinds of test. The pure functions are tested directly. The prose is held to the
repository: every count the blueprint quotes is recomputed here, every repository path a
reference names must exist, and every claim of the form "tests/x.py enforces this" must point
at a test that does. A kit that drifts from the repository it describes is worse than none.
"""
from __future__ import annotations

import datetime as dt
import re
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
KIT = ROOT / "cohort-kit"
SKILL = KIT / "skills" / "cohort-repo-setup"
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "lab-simulator"))
sys.path.insert(0, str(KIT / "scripts"))

import seed_content as seed  # noqa: E402
from cohort_schedule import (  # noqa: E402
    check,
    milestone_specs,
    render_ics,
    render_schedule,
    session_dates,
)
from unanswered_questions import Question, instructors, overdue, render  # noqa: E402

EXAMPLE = yaml.safe_load((KIT / "cohort.example.yaml").read_text())
NOW = dt.datetime(2026, 10, 20, 9, 0, tzinfo=dt.timezone.utc)


def kit_markdown() -> list[Path]:
    return sorted(p for p in KIT.rglob("*.md"))


# ───────────────────────────────────────────────────────────────── the skill ──
def test_skill_frontmatter_has_name_and_a_pushy_description():
    text = (SKILL / "SKILL.md").read_text()
    head = text.split("---")[1]
    meta = yaml.safe_load(head)
    assert meta["name"] == "cohort-repo-setup"
    # The description is the trigger. It has to name the phrases a person would actually say.
    for phrase in ("cohort", "Discussions", "boards", "L.A.B. Simulator", "traps"):
        assert phrase in meta["description"], phrase


def test_every_reference_the_skill_points_at_exists():
    text = (SKILL / "SKILL.md").read_text()
    for name in re.findall(r"`references/([a-z-]+\.md)`", text):
        assert (SKILL / "references" / name).exists(), name
    listed = {p.name for p in (SKILL / "references").glob("*.md")}
    pointed = set(re.findall(r"references/([a-z-]+\.md)", text))
    assert listed == pointed, f"unreferenced or missing: {listed ^ pointed}"


def test_skill_body_stays_under_the_progressive_disclosure_budget():
    assert len((SKILL / "SKILL.md").read_text().splitlines()) < 500


# ───────────────────────────────────────────── the prose is held to the repo ──
def test_blueprint_counts_are_the_repository_counts():
    """Every number the blueprint quotes is recomputed here. Update the blueprint, not the test."""
    text = (SKILL / "references" / "blueprint.md").read_text()
    units = [p for p in (ROOT / "lab-simulator" / "units").iterdir() if p.is_dir()]
    drills = [p for p in units if re.match(r"^[A-Z]D\d", p.name)]
    facts = {
        "Units (25 to 45 minutes, three gates) | " + str(len(units) - len(drills)): True,
        "Drills (5 to 15 minutes, one idea) | " + str(len(drills)): True,
        f"| Workflows | {len(list((ROOT / '.github' / 'workflows').glob('*.yml')))} |": True,
        f"| Discussion forms | {len(list((ROOT / '.github' / 'DISCUSSION_TEMPLATE').glob('*.yml')))} |": True,
        f"{len(seed.CATEGORIES)} custom categories": True,
        f"{len(seed.LABELS) + len(seed.DISCUSSION_LABELS)} labels": True,
        f"{len(seed.MILESTONES)} milestones": True,
        f"{len(seed.ISSUES)} issues": True,
        f"{len(seed.DISCUSSIONS)} threads": True,
        f"the Lifecycle board ({len(seed.LIFECYCLE)} practices)": True,
        f"| Categories | {6 + len(seed.CATEGORIES)}:": True,
    }
    missing = [line for line in facts if line not in text]
    assert not missing, missing


PLACEHOLDER = re.compile(r"[A-Z]{2,}|NN|week-0W|<")
# Paths that exist only in a cohort repository, generated by the kit. Named in the blueprint as
# "new for a cohort"; they are allowed to be absent from the reference repository.
COHORT_ONLY = ("docs/11-cohort/", "scripts/seed/threads_cohort.py", "calendar/", "resources/")


def test_repository_paths_named_in_the_kit_exist():
    """A backticked path under a real top-level directory must exist. Placeholders are skipped."""
    roots = ("docs/", "scripts/", "lab-simulator/", "tests/", ".github/", "cohort-kit/",
             "notebooks/", "raglab/")
    bad = []
    for md in kit_markdown():
        for path in re.findall(r"`([^`\s]+)`", md.read_text()):
            if not path.startswith(roots) or PLACEHOLDER.search(path):
                continue
            if path.startswith(COHORT_ONLY):
                continue
            path = path.split("#")[0].rstrip("/")
            if "*" in path or path.endswith((".yml`", ")")):
                continue
            if not (ROOT / path).exists():
                bad.append(f"{md.relative_to(ROOT)}: {path}")
    assert not bad, bad


def test_claims_about_tests_point_at_tests_that_exist():
    """'tests/test_x.py enforces …' is only true if the file has a test about the subject."""
    subjects = {
        "test_workflows.py": ["secrets", "REQUIRED_CHECKS", "DISCUSSION_TEMPLATE"],
        "test_seed_content.py": ["100"],
        "test_measurements.py": ["RD2"],
    }
    for name, needles in subjects.items():
        src = (ROOT / "tests" / name).read_text()
        for needle in needles:
            assert needle in src, f"{name} is claimed to cover {needle!r} and does not"


def test_kit_prose_has_no_em_dashes():
    """House style for cohort-facing text. The reference repository's own docs are exempt."""
    offenders = [str(p.relative_to(ROOT)) for p in kit_markdown() if "—" in p.read_text()]
    assert not offenders, offenders


def test_traps_are_numbered_without_gaps():
    rows = re.findall(r"^\| (\d+) \| \*\*", (SKILL / "references" / "traps.md").read_text(), re.M)
    assert [int(r) for r in rows] == list(range(1, len(rows) + 1))
    assert len(rows) >= 20


def test_prompts_all_invoke_the_skill_and_forbid_guessing():
    for p in sorted((KIT / "prompts").glob("*.md")):
        text = p.read_text()
        assert "cohort-repo-setup" in text, p.name


# ───────────────────────────────────────────────────────── cohort_schedule.py ──
def test_example_config_passes_check_against_this_repository():
    assert check(EXAMPLE, ROOT) == []


def test_check_names_every_problem_a_human_would_find_on_the_day():
    cfg = yaml.safe_load(yaml.safe_dump(EXAMPLE))
    cfg["sessions"][0]["prereads"].append("docs/does-not-exist.md")
    cfg["sessions"][1]["drills"].append("ZZ9")
    cfg["sessions"][2]["date"] = "2027-01-01"          # after ends
    cfg["people"][0]["role"] = "owner"
    problems = check(cfg, ROOT)
    assert any("does-not-exist" in p for p in problems)
    assert any("ZZ9" in p for p in problems)
    assert any("after cohort.ends" in p for p in problems)
    assert any("unknown role" in p for p in problems)


def test_sessions_land_on_the_weekly_day_unless_overridden():
    sessions = session_dates(EXAMPLE)
    for s in sessions[:-1]:
        assert s["date"].strftime("%A") == "Monday", s
    assert sessions[-1]["date"] == dt.date(2026, 11, 27)    # explicit override


def test_ics_is_utc_and_deterministic():
    ics = render_ics(EXAMPLE)
    assert ics.startswith("BEGIN:VCALENDAR\r\n")
    assert ics.count("BEGIN:VEVENT") == len(EXAMPLE["sessions"])
    assert "DTSTART:20261005T133000Z" in ics       # 19:00 Asia/Kolkata is 13:30 UTC
    assert render_ics(EXAMPLE) == ics


def test_schedule_page_says_it_is_generated_and_links_prereads():
    page = render_schedule(EXAMPLE)
    assert "Edit the YAML, not this page" in page
    assert "[client-zero](../../docs/00-orientation/client-zero.md)" in page


def test_milestones_are_one_per_session_with_a_due_date():
    specs = milestone_specs(EXAMPLE)
    assert len(specs) == len(EXAMPLE["sessions"])
    assert all(re.match(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", s["due_on"]) for s in specs)
    assert specs[0]["title"].startswith("Week 1 · ")


# ─────────────────────────────────────────────────────── unanswered_questions ──
def q(number, *, hours_old=48, answered=False, commenters=()):
    return Question(number=number, title=f"q{number}", url="u", author="learner",
                    created=NOW - dt.timedelta(hours=hours_old), answered=answered,
                    category="Q&A",
                    commenters=[(c, NOW - dt.timedelta(hours=1)) for c in commenters])


def test_instructors_are_the_maintain_and_admin_roles():
    assert instructors(EXAMPLE) == {"instructor-handle", "ta-handle"}


def test_overdue_is_unanswered_old_and_untouched_by_staff():
    staff = {"instructor-handle"}
    items = overdue([
        q(1),                                             # listed
        q(2, answered=True),                              # answered
        q(3, hours_old=3),                                # too new
        q(4, commenters=("Instructor-Handle",)),          # staff replied, case-insensitive
        q(5, commenters=("another-learner",)),            # a peer replied: still listed
        q(6, hours_old=200),                              # oldest first
    ], staff, NOW, hours=24)
    assert [i.number for i in items] == [6, 1, 5]


def test_render_is_instructor_facing_and_marks_itself():
    text = render(overdue([q(1)], set(), NOW), NOW, 24)
    assert text.startswith("<!-- cohort-kit:unanswered:v1 -->")
    assert "| 2.0d | Q&A | [q1](u) | @learner |" in text
    assert "mark the answer" in text
    assert "Nothing is waiting" in render([], NOW, 24)


# ───────────────────────────────────────────────────────── the workflow template ──
def test_alert_workflow_is_valid_and_keeps_secrets_out_of_ifs():
    wf = yaml.safe_load((KIT / "templates" / "workflows" / "unanswered-questions.yml").read_text())
    assert wf["permissions"] == {"contents": "read", "discussions": "read", "issues": "write"}
    for line in (KIT / "templates" / "workflows" / "unanswered-questions.yml").read_text().splitlines():
        assert not (re.match(r"\s*if:", line) and "secrets." in line), line
    assert "23 4 * * *" in yaml.safe_dump(wf), "schedule off the hour"


@pytest.mark.parametrize("name", ["PLAYBOOK.md", "IDEAS.md", "README.md", "cohort.example.yaml",
                                  "memory/user-CLAUDE.snippet.md", "templates/CLAUDE.md"])
def test_kit_top_level_files_exist(name):
    assert (KIT / name).exists()
